import type { CustomerBalance, Entry } from './types';
import { formatNaira } from './money';

function esc(v: string | number): string {
  const s = String(v);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

/** Pro: CSV of customers + balances + entries */
export function buildCsvExport(
  rows: CustomerBalance[],
  entriesByCustomer: Map<string, Entry[]>,
): string {
  const lines: string[] = [];
  lines.push(
    ['customer_id', 'customer_name', 'phone', 'balance_ngn', 'due_at', 'entry_count'].join(
      ',',
    ),
  );
  for (const row of rows) {
    const due = row.customer.dueAt
      ? new Date(row.customer.dueAt).toISOString()
      : '';
    lines.push(
      [
        esc(row.customer.id),
        esc(row.customer.name),
        esc(row.customer.phone || ''),
        esc((row.balanceKobo / 100).toFixed(2)),
        esc(due),
        esc(row.entryCount),
      ].join(','),
    );
  }

  lines.push('');
  lines.push(
    ['entry_id', 'customer_id', 'customer_name', 'type', 'amount_ngn', 'note', 'occurred_at'].join(
      ',',
    ),
  );
  for (const row of rows) {
    const entries = entriesByCustomer.get(row.customer.id) || [];
    for (const e of entries) {
      if (e.deletedAt) continue;
      lines.push(
        [
          esc(e.id),
          esc(e.customerId),
          esc(row.customer.name),
          esc(e.type),
          esc((e.amountKobo / 100).toFixed(2)),
          esc(e.note || ''),
          esc(new Date(e.occurredAt).toISOString()),
        ].join(','),
      );
    }
  }

  lines.push('');
  lines.push(`# Generated by DebtBook · ${new Date().toISOString()}`);
  lines.push(`# Amounts shown as Naira (e.g. ${formatNaira(150050)})`);
  return lines.join('\n');
}

export function downloadCsv(filename: string, csv: string): void {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
