import type { Customer, Entry, ShopProfile } from './types';
import { formatNaira } from './money';

function fmtDate(ts: number): string {
  return new Date(ts).toLocaleString('en-NG', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/** Plain-text customer statement for share/copy */
export function buildStatement(
  shop: ShopProfile,
  customer: Customer,
  entries: Entry[],
  balanceKobo: number,
): string {
  const lines: string[] = [];
  lines.push(shop.name.toUpperCase());
  lines.push('Customer Statement');
  lines.push('─'.repeat(28));
  lines.push(`Customer: ${customer.name}`);
  if (customer.phone) lines.push(`Phone: ${customer.phone}`);
  lines.push(`Date: ${fmtDate(Date.now())}`);
  lines.push('');
  lines.push('Transactions:');
  lines.push('─'.repeat(28));

  const sorted = [...entries]
    .filter((e) => !e.deletedAt)
    .sort((a, b) => a.occurredAt - b.occurredAt);

  if (sorted.length === 0) {
    lines.push('(no transactions)');
  } else {
    for (const e of sorted) {
      const sign = e.type === 'credit' ? '+' : '−';
      const label = e.type === 'credit' ? 'CREDIT' : 'PAYMENT';
      lines.push(`${fmtDate(e.occurredAt)}`);
      lines.push(`  ${label}  ${sign}${formatNaira(e.amountKobo)}`);
      if (e.note) lines.push(`  Note: ${e.note}`);
    }
  }

  lines.push('─'.repeat(28));
  const abs = formatNaira(Math.abs(balanceKobo));
  if (balanceKobo > 0) {
    lines.push(`BALANCE OWED: ${abs}`);
  } else if (balanceKobo < 0) {
    lines.push(`SHOP OWES CUSTOMER: ${abs}`);
  } else {
    lines.push('BALANCE: Settled (₦0.00)');
  }
  lines.push('');
  lines.push('Generated by DebtBook (offline)');
  return lines.join('\n');
}

export async function shareOrCopyText(text: string, title: string): Promise<'share' | 'clipboard' | 'none'> {
  if (typeof navigator !== 'undefined' && navigator.share) {
    try {
      await navigator.share({ text, title });
      return 'share';
    } catch {
      /* cancelled */
    }
  }
  if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return 'clipboard';
    } catch {
      /* ignore */
    }
  }
  return 'none';
}
